name = "OpenCLPicker"
uuid = "b4741b20-32dd-11e9-2e44-23e783dd72cb"
authors = ["Stephan Kleinboelting <skleinbo@thp.uni-koeln.de>"]
version = "0.1.0"

[deps]
OpenCL = "08131aa3-fb12-5dee-8b74-c09406e224a2"
